import SearchActor from "../front/component/searchActor"
import Navigation from "../front/component/navigation"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <SearchActor />
        {children}
      </body>
    </html>
  )
}
